
import FWCore.ParameterSet.Config as cms

source = cms.Source(
	"PoolSource",

	noEventSort = cms.untracked.bool(True),
	duplicateCheckMode = cms.untracked.string("noDuplicateCheck"),
	fileNames = cms.untracked.vstring()
)
source.fileNames.extend([
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_27.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_44.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_39.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_0.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_26.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_4.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_42.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_18.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_24.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_41.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_58.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_49.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_56.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_52.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_70.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_72.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_14.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_1.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_46.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_47.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_15.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_63.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_60.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_3.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_69.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_13.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_25.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_8.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_71.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_67.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_10.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_40.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_36.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_65.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_21.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_73.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_30.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_12.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_64.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_53.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_66.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_23.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_54.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_19.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_9.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_48.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_6.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_43.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_45.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_7.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_34.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_61.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_55.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_57.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_22.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_28.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_2.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_51.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_29.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_50.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_17.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_68.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_5.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_33.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_37.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_31.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_59.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_16.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_35.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_20.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_38.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_11.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_32.root',
		'file:/data/c/cbern/Analysis/Susy/CMSSW_3_8_5/src/CMGTools/SusyJetMET/Samples/MultiJetRun2010BPromptReco3/NoMETSkim/susyJetMET_tree_RA2_CMG_62.root',
])
