[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'cbern_mvamet_22May12'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_4Jul12'),
  ('CMGTools/External', 'UserCode/CMG/CMGTools/External', 'V00-02-02'),
  ('CMGTools/H2TauTau', 'UserCode/CMG/CMGTools/H2TauTau', 'cbern_nocctauele_4Jul12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_4Jul12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_4Jul12'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'V00-03-11'),
  ('CommonTools/RecoUtils', 'CommonTools/RecoUtils', 'V00-00-09'),
  ('CondFormats/EgammaObjects', 'CondFormats/EgammaObjects', 'V00-04-01'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'cbern_25Apr12'),
  ('EGamma/EGammaAnalysisTools', 'UserCode/EGamma/EGammaAnalysisTools', 'V00-00-13'),
  ('EGamma/EGammaAnalysisToolsSiXie', 'UserCode/sixie/EGamma/EGammaAnalysisTools', 'cbern_09May12'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ('FWCore/GuiBrowsers', 'FWCore/GuiBrowsers', 'V00-00-63'),
  ('HcalNoise/HcalLaserFilterFromAOD', 'HcalNoise/HcalLaserFilterFromAOD', 'HcalLaserFilter_20120510_YiChen'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('JetMETCorrections/Type1MET', 'JetMETCorrections/Type1MET', 'V04-06-09'),
  ('Muon/MuonAnalysisTools', 'UserCode/sixie/Muon/MuonAnalysisTools', 'V00-00-09'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-09-07'),
  ('PhysicsTools/PatUtils', 'PhysicsTools/PatUtils', 'V03-09-22'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-16'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-05-07'),
  ('RecoMET/METAnalyzers', 'RecoMET/METAnalyzers', 'V00-00-08'),
  ('RecoMET/METFilters', 'RecoMET/METFilters', 'V00-00-01'),
  ('RecoParticleFlow/PFProducer', 'RecoParticleFlow/PFProducer', 'V15-01-08'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'wreece_020512'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-04-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-04-17'),
  ('TauAnalysis/CandidateTools', 'TauAnalysis/CandidateTools', 'bMinimalSVfit_2012May13'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseMay18')]
# The following packages were not in the input release_info.
# Please make sure that the CVS module is correct!
#	CommonTools/RecoUtils                    V00-00-09
#	JetMETCorrections/Type1MET               V04-06-09
