[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'cbernForMike_muonmatrix_28Aug12'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_elevars_15Sep12'),
  ('CMGTools/External', 'UserCode/CMG/CMGTools/External', 'V00-02-09'),
  ('CMGTools/H2TauTau', 'UserCode/CMG/CMGTools/H2TauTau', 'cbern_12Sep12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_12Sep12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_eventselector_31Aug12'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'V00-03-16'),
  ('CommonTools/RecoAlgos', 'CommonTools/RecoAlgos', 'V00-03-23'),
  ('CommonTools/RecoUtils', 'CommonTools/RecoUtils', 'V00-00-12'),
  ('CondFormats/EgammaObjects', 'CondFormats/EgammaObjects', 'V00-04-01'),
  ('DataFormats/ParticleFlowCandidate', 'DataFormats/ParticleFlowCandidate', 'V15-03-02'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'V06-05-06'),
  ('DataFormats/TrackReco', 'DataFormats/TrackReco', 'V10-02-02'),
  ('DataFormats/VertexReco', 'DataFormats/VertexReco', 'V02-00-04'),
  ('EGamma/EGammaAnalysisTools', 'UserCode/EGamma/EGammaAnalysisTools', 'V00-00-13'),
  ('EGamma/EGammaAnalysisToolsSiXie', 'UserCode/sixie/EGamma/EGammaAnalysisTools', 'cbern_09May12'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ('JetMETCorrections/Type1MET', 'JetMETCorrections/Type1MET', 'V04-06-09'),
  ('Muon/MuonAnalysisTools', 'UserCode/sixie/Muon/MuonAnalysisTools', 'V00-00-09'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-09-33'),
  ('PhysicsTools/PatUtils', 'PhysicsTools/PatUtils', 'V03-09-23'),
  ('RecoMET/METAnalyzers', 'RecoMET/METAnalyzers', 'V00-00-08'),
  ('RecoMET/METFilters', 'RecoMET/METFilters', 'V00-00-07'),
  ('RecoParticleFlow/PFProducer', 'RecoParticleFlow/PFProducer', 'V15-02-09'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'wreece_020512'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-04-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-04-17'),
  ('TauAnalysis/CandidateTools', 'TauAnalysis/CandidateTools', 'V00-01-04s'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseMay18')]
