[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'michalis_100512_PFMuon'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_gt_15May12'),
  ('CMGTools/External', 'UserCode/CMG/CMGTools/External', 'V00-02-02'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_15May12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_yr_15May12'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'V00-03-08'),
  ('CondFormats/EgammaObjects', 'CondFormats/EgammaObjects', 'V00-04-01'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'cbern_25Apr12'),
  ('EGamma/EGammaAnalysisTools', 'UserCode/EGamma/EGammaAnalysisTools', 'V00-00-08'),
  ('EGamma/EGammaAnalysisToolsSiXie', 'UserCode/sixie/EGamma/EGammaAnalysisTools', 'cbern_09May12'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ('FWCore/GuiBrowsers', 'FWCore/GuiBrowsers', 'V00-00-63'),
  ('HcalNoise', 'UserCode/YiChen/HcalNoise', 'HcalLaserFilter_20120510_YiChen'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('Muon/MuonAnalysisTools', 'UserCode/sixie/Muon/MuonAnalysisTools', 'V00-00-09'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-09-02'),
  ('PhysicsTools/PatUtils', 'PhysicsTools/PatUtils', 'V03-09-18-03'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-16'),
  ('RecoMET/METFilters', 'RecoMET/METFilters', 'lhx_14APR2012_v1'),
  ('RecoMET/METAnalyzers', 'RecoMET/METAnalyzers', 'V00-00-08'),
  ('RecoParticleFlow/PFProducer', 'RecoParticleFlow/PFProducer', 'V15-01-06-01'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'wreece_020512'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-04-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-04-17')]
