[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'cbern_h2tautauvars_31Oct11'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_V2401_04Jan12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_CMSDataset_04Jan12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_rootdirstyle_01Nov11'),
  ('CMGTools/ZmumuJetsTutorial', 'UserCode/CMG/CMGTools/ZmumuJetsTutorial', 'cbern_tutorial_12Oct11'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'B4_2_X_cbern_dbetaoff_04Jan12_PFPileUpSpeed'),
  ('DataFormats/AnomalousEcalDataFormats', 'UserCode/csander/DataFormats/AnomalousEcalDataFormats', 'V110523_BE'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'V06-04-19-02'),
  ('GeneratorInterface/GenFilters', 'GeneratorInterface/GenFilters', 'V00-11-00-01'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('PhysicsTools/HepMCCandAlgos', 'PhysicsTools/HepMCCandAlgos', 'V11-03-16'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-06-48'),
  ('PhysicsTools/SelectorUtils', 'PhysicsTools/SelectorUtils', 'V00-03-24'),
  ('PhysicsTools/UtilAlgos', 'PhysicsTools/UtilAlgos', 'V08-02-14'),
  ('RecoJets/Configuration', 'RecoJets/Configuration', 'V02-04-17'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-03-07'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'Colin_June23'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-02-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-02-07'),
  ('RecoTauTag/TauTagTools', 'RecoTauTag/TauTagTools', 'V01-02-00'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'cbern_start_18Oct11') ]
