[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'michalis_bleedingedge_oct8'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_cleanup_13Nov12'),
  ('CMGTools/External', 'UserCode/CMG/CMGTools/External', 'cris_09Oct12'),
  ('CMGTools/H2TauTau', 'UserCode/CMG/CMGTools/H2TauTau', 'cbern_tuto_14Nov12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_Nov21'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_Nov21'),
  ('CMGTools/ZJetsTutorial', 'UserCode/CMG/CMGTools/ZJetsTutorial', 'cbern_Nov21'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'V00-03-16'),
  ('CommonTools/RecoAlgos', 'CommonTools/RecoAlgos', 'V00-03-24'),
  ('CommonTools/RecoUtils', 'CommonTools/RecoUtils', 'V00-00-12'),
  ('CondFormats/EgammaObjects', 'CondFormats/EgammaObjects', 'V00-04-01'),
  ('DataFormats/ParticleFlowCandidate', 'DataFormats/ParticleFlowCandidate', 'V15-03-04'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'V06-05-06-02'),
  ('DataFormats/TrackReco', 'DataFormats/TrackReco', 'V10-02-02'),
  ('DataFormats/VertexReco', 'DataFormats/VertexReco', 'V02-00-04'),
  ('EGamma/EGammaAnalysisTools', 'UserCode/EGamma/EGammaAnalysisTools', 'V00-00-29'),
  ('EGamma/EGammaAnalysisToolsSiXie', 'UserCode/sixie/EGamma/EGammaAnalysisTools', 'cbern_09May12'),
  ('EgammaAnalysis/ElectronTools', 'EgammaAnalysis/ElectronTools', 'FB_5Oct2012-2'),
  ('JetMETCorrections/Type1MET', 'JetMETCorrections/Type1MET', 'V04-06-09'),
  ('Muon/MuonAnalysisTools', 'UserCode/sixie/Muon/MuonAnalysisTools', 'V00-00-09'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-09-41'),
  ('PhysicsTools/PatUtils', 'PhysicsTools/PatUtils', 'V03-09-26'),
  ('RecoEgamma/EgammaTools', 'RecoEgamma/EgammaTools', 'V09-00-00'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V04-01-09'),
  ('RecoMET/METAnalyzers', 'RecoMET/METAnalyzers', 'V00-00-08'),
  ('RecoMET/METFilters', 'RecoMET/METFilters', 'V00-00-07'),
  ('RecoParticleFlow/PFProducer', 'RecoParticleFlow/PFProducer', 'V15-02-09'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'wreece_020512'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-04-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-04-17'),
  ('TauAnalysis/CandidateTools', 'TauAnalysis/CandidateTools', 'V00-01-04s'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseMay18')]
# The following packages were not in the input release_info.
# Please make sure that the CVS module is correct!
#	RecoLuminosity/LumiDB                    V04-01-09
