[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'patrick_pfchargedhadronvertex_18May12'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'patrick_allPhotons_18May12'),
  ('CMGTools/External', 'UserCode/CMG/CMGTools/External', 'V00-02-02'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'sezen_18may12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_rltinfo_18May12'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'V00-03-05-08'),
  ('CondFormats/EgammaObjects', 'CondFormats/EgammaObjects', 'V00-04-01'),
  ('DataFormats/METReco', 'DataFormats/METReco', 'lhx_12JAN2012_v1'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'V06-05-01'),
  ('DataFormats/TauReco', 'DataFormats/TauReco', 'CMSSW_5_2_4'),
  ('EGamma/EGammaAnalysisTools', 'UserCode/EGamma/EGammaAnalysisTools', 'V00-00-08'),
  ('EGamma/EGammaAnalysisToolsSiXie', 'UserCode/sixie/EGamma/EGammaAnalysisTools', 'cbern_09May12'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'UserCode/EGamma/EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing_V01'),
  ('FWCore/GuiBrowsers', 'FWCore/GuiBrowsers', 'V00-00-63'),
  ('GeneratorInterface/GenFilters', 'GeneratorInterface/GenFilters', 'V00-11-00-01'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('Muon/MuonAnalysisTools', 'UserCode/sixie/Muon/MuonAnalysisTools', 'V00-00-09'),
  ('PhysicsTools/HepMCCandAlgos', 'PhysicsTools/HepMCCandAlgos', 'V11-03-16'),
  ('PhysicsTools/IsolationAlgos', 'PhysicsTools/IsolationAlgos', 'V01-05-07'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-07-44'),
  ('PhysicsTools/PatUtils', 'PhysicsTools/PatUtils', 'V03-09-18-03'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-16'),
  ('RecoEgamma/ElectronIdentification', 'RecoEgamma/ElectronIdentification', 'V00-03-32'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-05-07'),
  ('RecoMET/METAnalyzers', 'RecoMET/METAnalyzers', 'V00-00-08'),
  ('RecoMET/METFilters', 'RecoMET/METFilters', 'lhx_14APR2012_v1'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'wreece_020512'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-04-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-04-17'),
  ('RecoTauTag/TauTagTools', 'RecoTauTag/TauTagTools', 'CMSSW_5_2_4'),
  ('TauAnalysis/CandidateTools', 'TauAnalysis/CandidateTools', 'bMinimalSVfit_2012May13'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseMay14')]
# The following packages were not in the input release_info.
# Please make sure that the CVS module is correct!
#	TauAnalysis/CandidateTools               bMinimalSVfit_2012May13
