[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'joseMarch20'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'lucie_21Mar12'),
  ('CMGTools/HToZZTo4Leptons', 'CMGTools/HToZZTo4Leptons', 'cbern_hzz_21Mar12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'pmeckiff21march2012'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_hzz_21Mar12'),
  ('CMGTools/ZmumuJetsTutorial', 'UserCode/CMG/CMGTools/ZmumuJetsTutorial', 'jhegeman_V2401_16Jan12'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-08-21'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-17'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-04-02'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'Colin_June23'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseNov14')]
