[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'wreece_220312'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_daniele_27Mar12'),
  ('CMGTools/H2TauTau', 'UserCode/CMG/CMGTools/H2TauTau', 'cbern_19Mar12'),
  ('CMGTools/HToZZTo4Leptons', 'UserCode/CMG/CMGTools/HToZZTo4Leptons', 'cbern_hzz_21Mar12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'pmeckiff26mar2012'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_hzz_21Mar12'),
  ('CMGTools/ZmumuJetsTutorial', 'UserCode/CMG/CMGTools/ZmumuJetsTutorial', 'jhegeman_V2401_16Jan12'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'V06-04-33'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'UserCode/ClaudeCharlot/EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'UserCode/ClaudeCharlot/EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing'),
  ('GeneratorInterface/GenFilters', 'GeneratorInterface/GenFilters', 'V00-11-00-01'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('PhysicsTools/HepMCCandAlgos', 'PhysicsTools/HepMCCandAlgos', 'V11-03-16'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-07-38-03'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-16'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-03-07'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'Colin_June23'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-02-12'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-02-16'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseNov14')]
