eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT100
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT150
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT200
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT250
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT300
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT350
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT400
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/gamma1jet_LO_pT550
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT100
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT150
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT200
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT250
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT300
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT350
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT400
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_LO_pT550
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT100
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT150
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT200
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT250
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT300
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT350
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT400
eos mkdir /store/cmst3/user/emanuele/monox/mcsamples/zjet_8tev/gen/z1jet_NLO_pT550
