[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'patrick_mvaDaniele_Feb28'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'patrick_mvaDaniele_Feb28'),
  ('CMGTools/H2TauTau', 'UserCode/CMG/CMGTools/H2TauTau', 'cbern_regcounters_27Feb12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_resubmit_02Mar12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_efflep_28Feb12'),
  ('CMGTools/ZmumuJetsTutorial', 'UserCode/CMG/CMGTools/ZmumuJetsTutorial', 'jhegeman_V2401_16Jan12'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('PhysicsTools/HepMCCandAlgos', 'PhysicsTools/HepMCCandAlgos', 'V11-03-16'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-07-38-02'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-16'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-03-07'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'Colin_June23'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-02-12'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-02-16'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseNov14')]
