[ ('AnalysisDataFormats/CMGTools', 'UserCode/CMG/AnalysisDataFormats/CMGTools', 'cbern_tauid_04May12'),
  ('CMGTools/Common', 'UserCode/CMG/CMGTools/Common', 'cbern_cmgonpat_06May12'),
  ('CMGTools/External', 'UserCode/CMG/CMGTools/External', 'V00-02-02'),
  ('CMGTools/H2TauTau', 'UserCode/CMG/CMGTools/H2TauTau', 'cbern_b_12Apr12'),
  ('CMGTools/HToZZTo4Leptons', 'UserCode/CMG/CMGTools/HToZZTo4Leptons', 'cbern_12Apr12'),
  ('CMGTools/Production', 'UserCode/CMG/CMGTools/Production', 'cbern_04May12'),
  ('CMGTools/RootTools', 'UserCode/CMG/CMGTools/RootTools', 'cbern_init_06May12'),
  ('CMGTools/ZmumuJetsTutorial', 'UserCode/CMG/CMGTools/ZmumuJetsTutorial', 'jhegeman_V2401_16Jan12'),
  ('CommonTools/ParticleFlow', 'CommonTools/ParticleFlow', 'V00-03-05-08'),
  ('CondFormats/EgammaObjects', 'CondFormats/EgammaObjects', 'V00-04-01'),
  ('DataFormats/PatCandidates', 'DataFormats/PatCandidates', 'V06-05-01'),
  ('DataFormats/TauReco', 'DataFormats/TauReco', 'CMSSW_5_2_4'),
  ('EGamma/EGammaAnalysisTools', 'UserCode/EGamma/EGammaAnalysisTools', 'V00-00-08'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'UserCode/ClaudeCharlot/EgammaCalibratedGsfElectrons/CalibratedElectronAlgos',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing'),
  ( 'EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'UserCode/ClaudeCharlot/EgammaCalibratedGsfElectrons/CalibratedElectronProducers',
    'Shervin20022012_2011Jan16ReRec0_and_Shervin05032012_Fall11MC_smearing'),
  ('FWCore/GuiBrowsers', 'FWCore/GuiBrowsers', 'V00-00-60'),
  ('GeneratorInterface/GenFilters', 'GeneratorInterface/GenFilters', 'V00-11-00-01'),
  ('JetMETAnalysis/ecalDeadCellTools', 'JetMETAnalysis/ecalDeadCellTools', 'Colin_TaggingMode_June30'),
  ('Muon/MuonAnalysisTools', 'UserCode/sixie/Muon/MuonAnalysisTools', 'V00-00-09'),
  ('PhysicsTools/HepMCCandAlgos', 'PhysicsTools/HepMCCandAlgos', 'V11-03-16'),
  ('PhysicsTools/IsolationAlgos', 'PhysicsTools/IsolationAlgos', 'V01-05-07'),
  ('PhysicsTools/PatAlgos', 'PhysicsTools/PatAlgos', 'V08-07-44'),
  ('PhysicsTools/PatUtils', 'PhysicsTools/PatUtils', 'V03-09-18-03'),
  ('PhysicsTools/Utilities', 'PhysicsTools/Utilities', 'V08-03-16'),
  ('RecoEgamma/ElectronIdentification', 'RecoEgamma/ElectronIdentification', 'V00-03-32'),
  ('RecoLuminosity/LumiDB', 'RecoLuminosity/LumiDB', 'V03-03-07'),
  ('RecoParticleFlow/PostProcessing', 'UserCode/RecoParticleFlow/PostProcessing', 'Colin_June23'),
  ('RecoTauTag/Configuration', 'RecoTauTag/Configuration', 'V01-04-03'),
  ('RecoTauTag/RecoTau', 'RecoTauTag/RecoTau', 'V01-04-17'),
  ('RecoTauTag/TauTagTools', 'RecoTauTag/TauTagTools', 'CMSSW_5_2_4'),
  ('TauAnalysis/SVFitStandAlone', 'UserCode/TauAnalysis/SVFitStandAlone', 'joseNov14')]
