C                                                                       
      INTEGER trig,debu,pryn,gzdc,gch1,gch2,gch3,ghhg,gchc
      REAL time,gene,gsmo,gsus,gsgu,ghcc,gfbw,gglu
      COMMON /h_cards/ trig(2),debu(2),time(1),gene(7),gsmo(6),         
     .                 gsus(11),pryn(10),gzdc(11),gch1(16),gch2(16),     
     .                 gch3(16),ghhg(2),ghcc(8),gchc(19),gsgu(7),
     .                 gfbw(4),gglu(1)
C
