import FWCore.ParameterSet.Config as cms

from CMGTools.Common.muon_cff import muonSequence
#NS should decide whether we put cmg in the names of the files / objects or not. put it everywhere
#NS in the script: put the namespace and the object type as they are to construct filenames and module names
#NS make sure the name of the python objects defined in a file reflect the name of the file. e.g. : cmgDiMuon_cfi should contain the module cmgDiMuon
from CMGTools.Common.factories.cmgDiMuon_cfi import cmgDiMuon
#NS histogram classes and modules should also be generated by the script
from CMGTools.Common.histograms.dimuonLorentzVector_cfi import dimuonLorentzVector

#NS for sequences: diMuon_cff can contain a variety of objects, and a sequence diMuonSequence 
diMuonSequence = cms.Sequence(
    muonSequence + 
    cmgDiMuon +
    dimuonLorentzVector
    )
